### ISSUE TITLE
Error saving as SVG

### ISSUE THREAD

**Issue by hpoit** [sisl/TikzGraphs.jl#10]
![image](https://cloud.githubusercontent.com/assets/3711100/19942033/76f5fd98-a119-11e6-98a5-38bcca075735.png)

**Comment by mykelk** [comment]
You need to have texlive installed and on your path.

**Comment by hpoit** [comment]
Hey Mykel. Thanks. Can it be MacTeX? For some reason the install-tl-unx.tar.gz was taking a very long time to install on OSX.

**Comment by mykelk** [comment]
I think mactex includes texlive.

**Comment by hpoit** [comment]
You're right, it does. I installed MacTeX, then `Pkg.build("TikzGraphs")`inside IJulia and ran the code again. Same error.

**Comment by hpoit** [comment]
Ran `Pkg.build("TikzGraphs")` in the REPL, and the code in IJulia, still the same.

**Comment by mykelk** [comment]
The binary lualatex needs to be on your path. If the command ;lualatex does not work, then Julia is not finding it on your path. Also, it is possible that your installation of mactex did not include lualatex, so you may have to install it through the mactex package manager.

**Comment by hpoit** [comment]
Hpoit-MBP:~ Corvus$ lualatex
This is LuaTeX, Version 0.95.0 (TeX Live 2016) 
 restricted system commands enabled.
**

Hi Mykel. It did work. Let me try plotting it again.

**Comment by hpoit** [comment]
Different error this time
![image](https://cloud.githubusercontent.com/assets/3711100/20242991/c26b7cbc-a92a-11e6-8142-99ad2519473c.png)

**Comment by mykelk** [comment]
You need pdf2svg installed. On Ubuntu, you can get this by running sudo apt-get install pdf2svg. On Windows, you can download the binaries from http://www.cityinthesky.co.uk/opensource/pdf2svg/. Be sure to add pdf2svg to your path (and restart).

**Comment by hpoit** [comment]
and for OSX?

**Comment by mykelk** [comment]
You can install through homebrew: brew install pdf2svg

**Comment by hpoit** [comment]
I installed it (thanks) and added /usr/local/Cellar/ to path. Same error.

**Comment by mykelk** [comment]
Did you restart IJulia completely? What does ;pdf2svg return? If the command isn't running, then it isn't seeing it on your path.

**Comment by hpoit** [comment]
I did. I added the path on bash terminal, checked that it was added, then restarted IJulia, and ran the block of code. I'm sorry, what do you mean by what does ;pdf2svg return? When you say run the command you mean on bash terminal?

**Comment by mykelk** [comment]
Run it in IJulia.

**Comment by hpoit** [comment]
Aha. /bin/bash: pdf2svg: command not found in IJulia!

Never thought I could add a path in IJulia. How do I do that?

**Comment by tawheeler** [comment]
You can see what it looks like by pulling BayesNets master and rendering a BN.

If the command is not being found then pdf2svg is either not installed or the path is not properly set.

**Comment by hpoit** [comment]
Hi Tim. I couldn't get to `brew install pdf2svg`
![image](https://cloud.githubusercontent.com/assets/3711100/22714672/bbf90500-ed74-11e6-80dc-5643d60d5a30.png)
I don't know what to do.

**Comment by tawheeler** [comment]
Well, that's your problem.

Permission denied suggests that you need sudo.

```
sudo brew install pdf2svg
```

You may also have to install cairo and/or poppler first:

```
brew install cairo
brew install poppler
```

**Comment by hpoit** [comment]
Thanks Tim, you're right. I added Cairo, Poppler, and pdf2svg with permissions, and this is what I got
![image](https://cloud.githubusercontent.com/assets/3711100/22737598/e57144bc-edea-11e6-993d-2ea6e9490bba.png)
![image](https://cloud.githubusercontent.com/assets/3711100/22737605/ec9fa62a-edea-11e6-9cfb-6d92d22b2888.png)

Also, I tried to permanently add the path with 
source $HOME/.bash_profile
. $HOME/.bash_profile
source ~/.bashrc 
. ~/.profile
but was unable to, the path going back to the old version every time I re-started the Terminal. What do you think I should do?

**Comment by mykelk** [comment]
That's the Julia console. Does it show up in Jupyter?

**Comment by tawheeler** [comment]
It will not display an image in the terminal. It should in a notebook.

**Comment by hpoit** [comment]
It does :-)
![image](https://cloud.githubusercontent.com/assets/3711100/22750882/8caac3ec-ee19-11e6-9fa8-76bfb818ec7a.png)
Thanks guys!

**Comment by tawheeler** [comment]
woo!
