### ISSUE TITLE
Undirected Graphs have edge arrows

### ISSUE THREAD

**Issue by tawheeler** [sisl/TikzGraphs.jl#14]
```
using TikzGraphs
using LightGraphs
g = Graph(4)
add_edge!(g, 1, 2)
add_edge!(g, 2, 3)
TikzGraphs.plot(g)
```

Undirected graphs are currently plotted with arrows.

**Comment by chelseas** [comment]
I seem to be having this problem again.

**Comment by mykelk** [comment]
@chelseas did you do `Pkg.checkout("TikzGraphs")`? I don't think a release has been tagged, so that's the only way to get it right now. We should tag something soon.

**Comment by chelseas** [comment]
I did that, but I'm still getting arrows. Not a huge deal, but here's an
example in an IJulia notebook.

**Comment by mykelk** [comment]
@chelseas it looks like the notebook was not attached.

**Comment by mykelk** [comment]
When I run your notebook, I get this:
![image](https://cloud.githubusercontent.com/assets/6294079/24085492/8308ea3e-0cba-11e7-9536-a81d2786e97e.png)
Are you sure you did `Pkg.checkout("TikzGraphs")` and not just `Pkg.add("TikzGraphs")`?
