### ISSUE TITLE
LaTeX env takes forever to install in Travis and breaks.

### ISSUE THREAD

**Issue by tawheeler** [sisl/TikzGraphs.jl#18]
Lualatex takes ~20 min to install when running a travis test.
It then fails with `lualatex -v` not being able to run.

**Comment by tawheeler** [comment]
Thanks for fixing. The Travis test is marked as pass despite this error:
"The program 'julia' is currently not installed. To run 'julia' please ask your administrator to install the package 'julia'"

**Comment by mykelk** [comment]
I fixed it so that it both runs lualatex and julia. It looks like it fails on 0.4 and 0.5.

**Comment by mykelk** [comment]
I think a7b881fc432fda36cd5abda2d1035b4c96cb0ebe fixes it (at least it does on my machine). Waiting for travis. I modified it to use `immutable` instead of `struct` at the moment since we're waiting for https://github.com/JuliaLang/Compat.jl/pull/338.
