### ISSUE TITLE
META not seeing v0.5.1

### ISSUE THREAD

**Issue by rcnlee** [sisl/TikzGraphs.jl#19]
``Pkg.update()`` doesn't seem to be pulling in ``v0.5.1`` which has the precompile flag enabled and depwarns removed.  It's breaking travis on downstream packages that use precompilation.  Can we update meta? or should I try to work around it?

**Comment by mykelk** [comment]
@tawheeler I just enabled attobot. I tried editing the release, but it doesn't look like it triggered a PR to METADATA. Would you mind taking a look?

**Comment by tawheeler** [comment]
I deleted the release and recreated it.
Attobot caught it: https://github.com/JuliaLang/METADATA.jl/pull/11766

**Comment by vchuravy** [comment]
I think the tag is wrong. https://github.com/JuliaLang/METADATA.jl/pull/11766#issuecomment-340069624
