### ISSUE TITLE
No Directory Available Error

### ISSUE THREAD

**Issue by chelseas** [sisl/TikzGraphs.jl#20]
I got this error trying to use TikzGraphs, not sure how to remedy it.

Error saving as SVG
could not spawn `lualatex --enable-write18 --output-directory=. tikzpicture`: no such file or directory (ENOENT)

This is my code:
`using LightGraphs`
`using TikzGraphs`
`g = Grid([5,5])`
`TikzGraphs.plot(g)`

**Comment by mykelk** [comment]
You need `lualatex` installed (ideally through texlive) and on your path. After that's done, confirm that it is on your path by running `;lualatex -v` (note the `;` to run a shell command). You may have to completely restart Jupyter from a fresh terminal so that you get the updated path.

**Comment by chelseas** [comment]
lualatex was already installed, I typed the following:
`lualatex -v`

And got the following output:
`lualatex -v
This is LuaTeX, Version beta-0.80.0 (TeX Live 2015/Debian) (rev 5238)

Execute  'luatex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

Copyright 2015 Taco Hoekwater, the LuaTeX Team.`

So my guess is that it's complaining about the output directory flag, which does look a bit weird to me:

`--output-directory=. tikzpicture`

**Comment by chelseas** [comment]
Ah nevermind, you were right. I was running the code on one server yesterday, and that server (jodhpur) doesn't seem to have texlive/lualatex, whereas I'm running on a different server today (tula) which does. My mistake. It works on tula.
