### ISSUE TITLE
How to resize inline graphs in ipynb?

### ISSUE THREAD

**Issue by Peter554** [sisl/TikzGraphs.jl#21]
Is there any easy way to do this with TikzGraphs graphs?

**Comment by mykelk** [comment]
I just added some functionality to pass options to TikzPictures.jl. Take a look at the end of the [documentation](http://nbviewer.jupyter.org/github/sisl/TikzGraphs.jl/blob/master/doc/TikzGraphs.ipynb). Does this enable what you want?

**Comment by mykelk** [comment]
I think you need to run `Pkg.checkout("TikzGraphs")` to get my new code. You will also have to restart your Julia kernel.

**Comment by Peter554** [comment]
Yes that works thanks :)
