### ISSUE TITLE
Non-unique labels

### ISSUE THREAD

**Issue by tawheeler** [sisl/TikzGraphs.jl#5]
Non-unique labels no not result in the correct graph:

```
g = DiGraph(3)
add_edge!(g, 1, 2)
add_edge!(g, 1, 3)
TikzGraphs.plot(g, ["+", "a", "a"])
```

This can certainly be bypassed with pure Tikz; not sure whether the graphs package would support something like this. We could throw a warning if it cannot be solved.

**Comment by mykelk** [comment]
Ah, this should be easy to fix.
