### ISSUE TITLE
Nodes are amalgamated if they have the same label

### ISSUE THREAD

**Issue by dpsanders** [sisl/TikzGraphs.jl#8]
I am trying to draw a syntax tree where different nodes have the same label.
Those nodes seem to get amalgamated into one.

**Comment by mykelk** [comment]
Support for repeated labels was added recently. See: http://nbviewer.jupyter.org/github/sisl/TikzGraphs.jl/blob/master/doc/TikzGraphs.ipynb

I haven't tagged a release, but I should do that. For now, just do Pkg.checkout("TikzGraphs").

**Comment by dpsanders** [comment]
Thanks, but it still doesn't work after the `checkout`.

**Comment by mykelk** [comment]
Can you send me a code snippet that results in this failure?

**Comment by mykelk** [comment]
And I assumed you restarted your kernel?

**Comment by dpsanders** [comment]
Oh, sorry, it's working now -- thanks a lot!

**Comment by dpsanders** [comment]
Please do tag a new release. This is a very nice package!

**Comment by dpsanders** [comment]
You might like to check out 

https://gist.github.com/dpsanders/5cc1acff2471d27bc583916e00d43387

Feel free to add this to your docs if you would like!

**Comment by mykelk** [comment]
Hey! I like your syntax tree plot! I just tagged a release.
